name: Build and Release .NET Application

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x.x'

    - name: Restore dependencies
      run: dotnet restore LZTraining.sln

    - name: Build
      run: dotnet build LZTraining.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish LZTrainingGamesDownloader/LZTrainingGamesDownloader.fsproj --configuration Release --no-build --output ./output

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-release
        path: ./output

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Windows artifacts
      uses: actions/download-artifact@v2
      with:
        name: windows-latest-release
        path: ./windows

    - name: Download Linux artifacts
      uses: actions/download-artifact@v2
      with:
        name: ubuntu-latest-release
        path: ./linux

    - name: Download macOS artifacts
      uses: actions/download-artifact@v2
      with:
        name: macos-latest-release
        path: ./macos

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Windows release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./windows
        asset_name: windows-release.zip
        asset_content_type: application/zip

    - name: Upload Linux release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./linux
        asset_name: linux-release.zip
        asset_content_type: application/zip

    - name: Upload macOS release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./macos
        asset_name: macos-release.zip
        asset_content_type: application/zip

